#!/usr/bin/env bash
# looping best school ten times but there differnet text on the 4th and 8th line
while [ $i -le 10 ]
do
     if [ $i -eq 4 ];
     then
        echo "bad luck"

        elif [ $i -eq 8 ];
	then
	  echo "good luck"
	  else
	      echo "Best School"
	 fi
	 ((i++))
done