#!/usr/bin/env bash
# a loop that goes 1-20 and has phrases thoughout
i=1
while [ $i -le 20 ]
do
echo $i
case $i in
     4)
     echo "bad luck from China"
     ;;
     9)
     echo "bad luck from Japan"
     ;;
     17)
     echo "bad luck from Italy"
     ;;
esac
   ((i++))
done
